### ISSUE TITLE
checksum mismatch

### ISSUE THREAD

**Issue by linuxdan** [ghoneycutt/puppet-module-selinux#23]
md5sum ghoneycutt-selinux-1.1.0/metadata.json says :
01ba0871c3e78ffa3e006093992e36a0  ghoneycutt-selinux-1.1.0/metadata.json

But ghoneycutt-selinux-1.1.0/checksums.json says:
"metadata.json": "c09bb4419416105dd48145b0bd50e623",

**Comment by ghoneycutt** [comment]
New version is out
